-
  name:                Instalacja PostgreSQL CL
  hosts:               all
  remote_user:         root
  become:              yes
  tasks:

 ## Instalacja PostgreSQL CL 12

   - name: Add an Apt signing key, uses whichever key is at the URL
     apt_key:
       url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
       state: present
     ignore_errors:   yes

   - name: Add Postgresql 12 apt repository
     apt_repository:
       repo: 'deb http://apt.postgresql.org/pub/repos/apt/ eoan-pgdg main'
       state: present

   - name:            Installacja wymaganych komponentow
     apt:
       update_cache:  yes
       name:          "{{ item }}"
       state:         present
     with_items:
     - htop
     - mc
     - screen
     - nmon
     - iftop
     - tcpdump
     - unzip
     - curl
     - postgresql-12
     - postgresql-client-12
